/* DON'T EDIT THIS FILE. This is generated by 'scripts/lib/update-lib-index.ts' */
import { recommended } from './configs/recommended'
import banAdblockAttrs from './rules/ban-adblock-attrs'

export const configs = {
  recommended,
}

export const rules = {
  'ban-adblock-attrs': banAdblockAttrs,
}
